# Generated by Django 5.0 on 2025-11-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('sku', models.CharField(help_text='Stock Keeping Unit (SKU) code', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('stock_qty', models.PositiveIntegerField(default=0, help_text='Current stock quantity')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is currently available for sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('credit', 'Credit'), ('other', 'Other')], default='cash', help_text='Payment method used', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='paid', help_text='Payment status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Order notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client who made the purchase (optional for walk-ins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity ordered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of sale', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Line item total (quantity * unit_price)', max_digits=10)),
                ('appointment', models.ForeignKey(blank=True, help_text='Linked appointment (if service was booked)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='appointments.appointment')),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.order')),
                ('service', models.ForeignKey(blank=True, help_text='Service being ordered (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='appointments.service')),
                ('product', models.ForeignKey(blank=True, help_text='Product being ordered (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pos.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
