# Generated by Django 5.0 on 2025-11-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost (quantity * unit_cost) for profit calculation', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit at time of sale (for profit calculation)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Product cost price (for profit calculation)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Product selling price', max_digits=10),
        ),
    ]
