# Generated by Django 5.0 on 2025-11-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_orderitem_total_cost_orderitem_unit_cost_and_more'),
    ]

    operations = [
    ]
