# Generated by Django 5.0 on 2025-11-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_update_existing_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10),
        ),
    ]
