# Generated by Django 5.0 on 2025-11-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Date of the appointment')),
                ('appointment_time', models.TimeField(help_text='Start time of the appointment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Appointment status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Service description', null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, help_text='Service price', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the service is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('last_name', models.CharField(help_text='Last name', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('specialization', models.CharField(blank=True, help_text='Staff specialization or title', max_length=200, null=True)),
                ('bio', models.TextField(blank=True, help_text='Staff bio', null=True)),
                ('monday_start', models.TimeField(blank=True, help_text='Monday start time', null=True)),
                ('monday_end', models.TimeField(blank=True, help_text='Monday end time', null=True)),
                ('tuesday_start', models.TimeField(blank=True, help_text='Tuesday start time', null=True)),
                ('tuesday_end', models.TimeField(blank=True, help_text='Tuesday end time', null=True)),
                ('wednesday_start', models.TimeField(blank=True, help_text='Wednesday start time', null=True)),
                ('wednesday_end', models.TimeField(blank=True, help_text='Wednesday end time', null=True)),
                ('thursday_start', models.TimeField(blank=True, help_text='Thursday start time', null=True)),
                ('thursday_end', models.TimeField(blank=True, help_text='Thursday end time', null=True)),
                ('friday_start', models.TimeField(blank=True, help_text='Friday start time', null=True)),
                ('friday_end', models.TimeField(blank=True, help_text='Friday end time', null=True)),
                ('saturday_start', models.TimeField(blank=True, help_text='Saturday start time', null=True)),
                ('saturday_end', models.TimeField(blank=True, help_text='Saturday end time', null=True)),
                ('sunday_start', models.TimeField(blank=True, help_text='Sunday start time', null=True)),
                ('sunday_end', models.TimeField(blank=True, help_text='Sunday end time', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the staff member is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
