# Generated by Django 5.0 on 2025-11-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(help_text='Client who booked the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(help_text='Service being booked', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(help_text='Staff member assigned to the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.staffmember'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('staff', 'appointment_date', 'appointment_time'), name='unique_staff_appointment_time'),
        ),
    ]
