# Generated by Django 5.0 on 2025-11-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sessions_required',
            field=models.PositiveIntegerField(default=1, help_text='Number of sessions required for this service (e.g., Laser = 6, PRP = 3)'),
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_completed', models.PositiveIntegerField(default=0, help_text='Number of sessions completed')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether all sessions are completed')),
                ('assigned_date', models.DateField(auto_now_add=True, help_text='Date when package was assigned')),
                ('completed_date', models.DateField(blank=True, help_text='Date when package was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('client', models.ForeignKey(help_text='Client assigned to this package', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.client')),
            ],
            options={
                'verbose_name': 'Client Package',
                'verbose_name_plural': 'Client Packages',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_package',
            field=models.ForeignKey(blank=True, help_text='Linked package (if session belongs to a package)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.clientpackage'),
        ),
        migrations.CreateModel(
            name='ClientServiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_completed', models.PositiveIntegerField(default=0, help_text='Number of sessions completed')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether all required sessions are completed')),
                ('started_date', models.DateField(auto_now_add=True, help_text='Date when service sessions started')),
                ('completed_date', models.DateField(blank=True, help_text='Date when all sessions were completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('client', models.ForeignKey(help_text='Client', on_delete=django.db.models.deletion.CASCADE, related_name='service_sessions', to='core.client')),
                ('service', models.ForeignKey(help_text='Service', on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='appointments.service')),
            ],
            options={
                'verbose_name': 'Client Service Session',
                'verbose_name_plural': 'Client Service Sessions',
                'ordering': ['-started_date'],
                'unique_together': {('client', 'service')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_service_session',
            field=models.ForeignKey(blank=True, help_text='Linked service session tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.clientservicesession'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Package name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Package description', null=True)),
                ('total_sessions', models.PositiveIntegerField(help_text='Total number of sessions in this package')),
                ('price', models.DecimalField(decimal_places=2, help_text='Package price', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the package is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(help_text='Services included in this package (3-5 services)', related_name='packages', to='appointments.service')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clientpackage',
            name='package',
            field=models.ForeignKey(help_text='Package assigned', on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='appointments.package'),
        ),
        migrations.AlterUniqueTogether(
            name='clientpackage',
            unique_together={('client', 'package')},
        ),
    ]
