# Generated by Django 5.0 on 2025-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_service_sessions_required_clientpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original package price (before discount)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Package price (after discount)', max_digits=10),
        ),
    ]
