# Generated by Django 5.0 on 2025-11-23 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_package_original_price_alter_package_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='email',
        ),
    ]
